---
title: "pandas (R)osetta: Tidyverse R"
subtitle: "Intro to R and Tidyverse for Pandas users and vice versa."
author: "Lisa Malins"
output:
  github_document:
    toc: true
  html_document:
    toc: true
    toc_float: true
    df_print: paged
  pdf_document:
    toc: true
    toc_depth: 4
    df_print: "tibble"
---

&nbsp;

This is a demonstration of basic data wrangling operations in Tidyverse R.

Sister notebooks demonstrate the exact same operations in base R and the Pandas library in Python, just like the Rosetta Stone.

## I/O
### Create dataframe from scratch
```{r}
suppressPackageStartupMessages(library("dplyr"))
tbl <- tibble(
  letter = c("a", "b", "c", "d", "e"),
  number = c(1:5),
  fruit = c("apple", "banana", "coconut", "date", "elderberry"),
  vegetable = c("arugula", "beet", "carrot", "daikon", "eggplant"),
  name = c("Alice", "Bob", "Carol", "Dan", "Eve")
)
tbl
```

### Write
```{r}
library("readr")
write_csv(tbl, "data/tidy_letters.csv")
write_tsv(tbl, "data/tidy_letters.tsv")
```

### Read
```{r}
library("readr")
read_csv("data/tidy_letters.csv")
read_tsv("data/tidy_letters.tsv")
```
